package de.mimuc.pem_music_graph.list;

public enum Genre {
	MUSIC,
	POP, 
	ALTERNATIVE, PUNK, INDUSTRIAL, BRITPOP, 
	DANCEELECTRO, EXTREM, TECHNO, DUBSTEP, 
	HIPHOPRAP, 
	BLACK, 
	ROCKMETAL, METAL, PROGRESSIVE, HARDROCK;
}
